tracking_link:
  "Default Web Link": "Default link"
  "Data Science Slack": "Slack"
  "RAP Champions": "RAP Champions"
  "Profession Newsletter": "Profession newsletters/mailing lists"
  "Internal ONS": "ONS Networks"

workplace:
  question: "Where do you primarily work?"
  cols: workplace
  levels: ["Civil service, including devolved administrations",
           "NHS or local healthcare service",
           "Other"]

cs_grade:
  question: "What is your civil service grade?"
  cols: cs_grade
  levels: ["SCS Pay Band 1 (or equivalent)",
          "Grade 6 (or equivalent)",
          "Grade 7 (or equivalent)",
          "Senior Executive Officer (or equivalent)",
          "Higher Executive Officer (or equivalent)",
          "Executive Officer (or equivalent)",
          "Administrative Officer (or equivalent)",
          "Fast Stream",
          "Other (please specify)"]



department:
  question: "Which Civil Service department do you primarily work in?"
  cols: department
  levels: ["Attorney General's Office",
          "Cabinet Office (excl. agencies)",
          "Department for Business & Trade (excl. agencies)",
          "Department for Culture, Media & Sport",
          "Department for Education (excl. agencies)",
          "Department for Energy Security & Net Zero",
          "Department for Environment Food & Rural Affairs (excl. agencies)",
          "Department for Science, Innovation & Technology (excl. agencies)",
          "Department for Transport (excl. agencies)",
          "Department for Work & Pensions",
          "Department of Health & Social Care (excl. agencies)",
          "Foreign, Commonwealth & Development Office (excl. agencies)",
          "HM Treasury (excl. agencies)",
          "Home Office",
          "Ministry of Defence (excl. agencies)",
          "Ministry of Housing, Communities & Local Government (excl. agencies)",
          "Ministry of Justice (excl. agencies)",
          "Northern Ireland Office",
          "Office of the Advocate General for Scotland",
          "Office of the Leader of the House of Commons",
          "Office of the Leader of the House of Lords",
          "Office of the Secretary of State for Scotland",
          "UK Export Finance",
          "Wales Office",
          "The Charity Commission",
          "Competition and Markets Authority",
          "Crown Prosecution Service",
          "Food Standards Agency",
          "Forestry Commission (excl. agencies)",
          "Government Actuary's Department",
          "Government Legal Department",
          "HM Land Registry",
          "HM Revenue & Customs (excl. agencies)",
          "NS&I",
          "The National Archives",
          "National Crime Agency",
          "Office of Rail and Road",
          "Ofgem",
          "Ofqual",
          "Ofsted",
          "Serious Fraud Office",
          "Supreme Court of the United Kingdom",
          "UK Statistics Authority",
          "The Water Services Regulation Authority (Ofwat)",
          "Prime Minister's Office, 10 Downing Street",
          "Crown Commercial Service",
          "Government Property Agency",
          "Companies House",
          "The Insolvency Service",
          "Building Digital UK",
          "Intellectual Property Office",
          "Met Office",
          "UK Space Agency",
          "Planning Inspectorate",
          "Queen Elizabeth II Conference Centre",
          "Education and Skills Funding Agency",
          "Teaching Regulation Agency",
          "Standards and Testing Agency",
          "Animal and Plant Health Agency",
          "Centre for Environment, Fisheries and Aquaculture Science",
          "Rural Payments Agency",
          "Veterinary Medicines Directorate",
          "Active Travel England",
          "Driver and Vehicle Licensing Agency",
          "Driver and Vehicle Standards Agency",
          "Maritime and Coastguard Agency",
          "Vehicle Certification Agency",
          "Medicines and Healthcare products Regulatory Agency",
          "UK Health Security Agency",
          "Wilton Park",
          "Government Internal Audit Agency",
          "National Infrastructure Commission",
          "UK Debt Management Office",
          "Defence Electronics and Components Agency",
          "Defence Equipment and Support",
          "Defence Science and Technology Laboratory",
          "UK Hydrographic Office",
          "Submarine Delivery Agency",
          "Criminal Injuries Compensation Authority",
          "HM Courts & Tribunals Service",
          "HM Prison and Probation Service",
          "Legal Aid Agency",
          "Office of the Public Guardian",
          "Forest Research",
          "Forestry England",
          "Valuation Office Agency",
          "Office for National Statistics",
          "Northern Ireland Executive",
          "Scottish Government (excl. agencies)",
          "Welsh Government",
          "Accountant in Bankruptcy",
          "Disclosure Scotland",
          "Education Scotland",
          "Forestry and Land Scotland",
          "Scottish Forestry",
          "Scottish Prison Service",
          "Scottish Public Pensions Agency",
          "Social Security Scotland",
          "Student Awards Agency for Scotland",
          "Transport Scotland"]


professions:
  question: "Do you belong to any of these civil service professions?"
  cols:
    prof_DE: "Data Engineers"
    prof_DS: "Data Scientists"
    prof_GDD: "Government Digital and Data"
    prof_GAD: "Government Actuary's Department"
    prof_GES: "Government Economic Service"
    prof_geog: "Government Geography Profession"
    prof_GORS: "Government Operational Research Service"
    prof_GSE: "Government Science & Engineering"
    prof_GSR: "Government Social Research"
    prof_GSG: "Government Statistician Group"
    prof_none: "Civil Service, no profession membership"
    prof_other: "Other Civil Service profession"
  levels: ["Yes", "No"]

ons_directorate:
  question: "Which ONS directorate do you belong to?"
  cols: ons_directorate
  levels: ["Business Surveys",
            "Communications & Digital Publishing",
            "Data Growth and Operations",
            "Digital Services",
            "Economic Statistics Production and Analysis",
            "Finance, Planning & Performance",
            "Integrated Data Programme",
            "Macroeconomic and Environment Statistics and Analysis",
            "Methodology and Quality",
            "Office of the National Statistician",
            "People & Business Services",
            "Population Statistics",
            "Public Policy Analysis",
            "Security and information Management",
            "Social Surveys",
            "Strategy, Planning, Innovation, Delivery, Assurance and Support",
            "Other"]

pay_band:
  question: "Which pay bands cover your role?"
  levels: ["NHS",
          "Local Authority or NJC",
          "Other / Not sure"]

nhs_band:
  question: "What is your NHS band (or equivalent)?"
  levels: ["Band 2",
          "Band 3",
          "Band 4",
          "Band 5",
          "Band 6",
          "Band 7",
          "Band 8a",
          "Band 8b",
          "Band 8c",
          "Band 8d",
          "Band 9"]

njc_grade:
  question: "What is your local authority or NJC grade (or equivalent)?"
  levels: ["Grade 1",
          "Grade 2",
          "Grade 3",
          "Grade 4",
          "Grade 5",
          "Grade 6",
          "Grade 7",
          "Grade 8",
          "Grade 9",
          "Grade 10",
          "Grade 11",
          "Other"]

time_in_role:
  question: "How long have you been in your current role?"
  levels: ["Less than 1 year",
            "Between 1 and 3 years",
            "Between 3 and 5 years",
            "Over 5 years"]

coding_exp:
  question: "Do you have any coding experience?"
  levels: ["Yes",
          "No"]

team:
  question: "Do you regularly work with people who write code to complete their work?"
  levels: ["Yes",
          "No"]

manage_project:
  question: "Would you feel confident managing a coding project?"
  levels: ["Yes",
          "No",
          "Not sure"]

coding_learn_pref:
  question: "Would you like to use coding in your current role?"
  levels: ["Yes",
          "No",
          "Not sure / not applicable"]

coding_learn_barriers:
  question: "What are the barriers, if any, to you learning to code in your current role?"
  levels: ["Yes",
           "No"]
  cols:
    learn_avail_resource: "Availability of resources"
    learn_suit_resources: "Suitability of resources"
    learn_opportunity: "Lack of opportunity"
    learn_tools: "Availability of tools"
    learn_manager_support: "Lack of management support"
    learn_peer_support: "Lack of peer support"
    learn_no_barrier: "No barriers/not applicable"
    learn_other_barrier: "Other"

coding_years:
  question: "How many years of professional coding experience do you have?"
  levels: ["None",
          "Less than 1 year",
          "Between 1 and 3 years",
          "Between 3 and 5 years",
          "Over 5 years"]

code_freq:
  question: "In your current role, how often do you write code to complete your work objectives?"
  levels: ["Never",
          "Rarely",
          "Sometimes",
          "Regularly",
          "Always"]

coding_freq_pref:
  question: "Would you prefer to use more coding in your role?"
  levels: ["Yes",
          "No",
          "Not sure / not applicable"]

ability_change:
  question: "How has your coding ability changed during your current role?"
  levels: ["It has become significantly better",
          "It has become slightly better",
          "It has stayed the same",
          "It has become slightly worse",
          "It has become significantly worse"]

coding_improve_barriers:
  question: "What are the barriers, if any, to improving your coding skills in your current role"
  levels: ["Yes",
           "No"]
  cols:
    improve_avail_resources: "Availability of resources"
    improve_suit_resources: "Suitability of resources"
    improve_opportunity: "Lack of opportunity"
    improve_tools: "Availability of tools"
    improve_manager_support: "Lack of management support"
    improve_peer_support: "Lack of peer support"
    improve_no_barrier: "No barriers/not applicable"
    improve_other_barrier: "Other"

coding_tools_knowledge:
  question: "Which of these tools do you know how to use"
  levels: ["Yes",
            "No"]
  cols:
    knowledge_python: "Python"
    knowledge_R: "R"
    knowledge_dax: "DAX"
    knowledge_matlab: "Matlab"
    knowledge_SAS: "SAS"
    knowledge_SPSS: "SPSS"
    knowledge_SQL: "SQL"
    knowledge_stata: "Stata"
    knowledge_spark: "Spark"
    knowledge_VBA: "VBA"
    knowledge_other: "Other"

coding_tools_use:
  question: "Which of these tools do you use in your current role"
  levels: ["Yes",
            "No"]
  cols:
    use_python: "Python"
    use_R: "R"
    use_dax: "DAX"
    use_matlab: "Matlab"
    use_SAS: "SAS"
    use_SPSS: "SPSS"
    use_SQL: "SQL"
    use_stata: "Stata"
    use_spark: "Spark"
    use_VBA: "VBA"
    use_other: "Other"

git:
  question: "Do you know how to use Git"
  levels: ["Yes, I use it in my current role",
          "Yes, but I don't use it in my current role",
          "No"]

cloud:
 question: "Do you use any cloud data platforms or services in your current role?"
 levels: ["Yes",
          "No"]
 cols:
  google: "Google (e.g. GCP)"
  amazon: "Amazon (e.g. AWS)"
  microsoft: "Microsoft (e.g. Azure)"
  cloudera: "Cloudera"
  databricks: "Databricks"
  cloud_none: "None"
  cloud_other: "Other"

ai:
  question: "Do you use any AI assistants when coding at work?"
  levels: ["Yes",
          "No"]

ai_tools:
  question: "Which of the following AI assistants do you use when coding in your current role?"
  levels: ["Yes",
          "No"]
  cols:
    ai_gpt: "ChatGPT"
    ai_github: "GitHub Copilot"
    ai_google: "Google Gemini"
    ai_microsoft: "Microsoft Copilot"
    ai_claude: "Claude"
    ai_codex: "OpenAI Codex"
    ai_other: "Other"

ai_use:
  question: "When coding at work, how often do you use AI assistants for the following tasks"
  levels: ["Never",
          "Rarely",
          "Sometimes",
          "Regularly",
          "Always"]
  cols:
    ai_use_write: "Writing code"
    ai_use_debug: "Debugging code"
    ai_use_doc: "Documenting code"
    ai_use_question: "Getting answers to a coding question"
    ai_use_testing: "Testing code"
    ai_use_learn: "Learning about new concepts"
    ai_use_other: "Other"

ai_impact:
  question: "What impact, if any, has AI had on your coding at work?"

coding_practices:
  question: "When coding in your current role, how often do you do the following?"
  levels: ["Not sure / not applicable",
          "Never",
          "Rarely",
          "Sometimes",
          "Regularly",
          "Always"]
  cols:
    prac_open_source: "Use open source software"
    prac_code_style: "Use a standard code style"
    prac_functions: "Write functions"
    prac_control_flow: "Use control flow"
    prac_config: "Separate settings from code"
    prac_review: "Have code reviewed"
    prac_manual_tests: "Manually test code"
    prac_auto_tests: "Write automated tests"

working_practices:
  question: "When coding in your current role, how often do you do the following?"
  levels: ["Not sure / not applicable",
          "Never",
          "Rarely",
          "Sometimes",
          "Regularly",
          "Always"]
  cols:
    work_git: "Use version control"
    work_succession: "Have a succession plan"
    work_aims: "Understand project aims"
    work_roles: "Understand project roles"
    work_publish_code: "Publish code in the open"
    work_qa: "Work to quality standards"

doc:
  question: "When coding in your current role, how often do you do the following?"
  levels: ["Not sure / not applicable",
          "Never",
          "Rarely",
          "Sometimes",
          "Regularly",
          "Always"]
  cols:
    doc_readme: "Create README files"
    doc_function: "Document functions"
    doc_dependencies: "Document dependencies"
    doc_design: "Document pipeline design"
    doc_qa: "Document manual QA steps"

rap_implementing:
  question: "To what extent to you agree with the following statement: 'I am currently implementing RAP in my work' "
  levels: ["Strongly Disagree",
          "Disagree",
          "Neutral",
          "Agree",
          "Strongly Agree"]

rap_barriers:
  question: "What, if any, are the main barriers to you implementing RAP in your current role?"
  levels: ["Yes",
           "No"]
  cols:
    rap_tools: "Availability of tools"
    rap_management: "Lack of management support"
    rap_skills: "Current skills"
    rap_guidance: "Lack of guidance"
    rap_time: "Not enough time"
    rap_peer_support: "Lack of peer support"
    rap_unsuited: "Work not suited to RAP"
    rap_none: "No barriers"
    rap_other: "Other"

standards:
  question: "Do you work to any analysis or coding quality standards?"
  levels: ["Yes, internal to my organisation",
           "Yes, Civil Service or other external standards",
           "Yes. both internal external and external standards",
           "No, I am not aware of any",
           "Not sure"]

duck_book:
  question: "Are you aware of the 'Duck Book' (Quality Assurance of Code for Analysis and Research?)"
  levels: ["Yes, I use it",
           "Yes, but I don't use it",
           "No"]

packages:
  question: "Do you or your team use any cross-government or department-specific analysis packages in your work?"
  levels: ["Yes",
          "No",
          "Not sure or not applicable"]

packages_list:
  question: "If you know of any useful public sector analysis packages, please add a link here"

qs_aware:
  question: "The ONS Quality Standard for Analysis gives the minimal standard of quality expected for all analysis in ONS. How aware, if at all, are you of the Quality Standard?"
  levels: ["I am aware of the Quality Standard",
           "I am not aware of the Quality Standard"]

qs_comply:
  question: "Overall, how does any analysis you produce comply with the Quality Standard?"
  levels: ["I don’t produce analysis",
          "The analysis I produce does not comply with the Quality Standard at all",
          "I’m not sure if analysis complies with the Quality Standard",
          "The analysis I produce partly complies with the Quality Standard",
          "The analysis I produce complies fully with the Quality Standard"]

qq_aware:
 question: "The ONS Quality Questions have been designed to help analysts assure their work so that it complies with the ONS Quality Standard. Which statement best describes your experience of the ONS Quality Questions?"
 levels: ["I am aware of the ONS Quality Questions but don’t use them",
          "I am aware of the ONS Quality Questions and use them",
          "I am not aware of the ONS Quality Questions"]

comments:
  question: "Do you have any further comments on your experiences with coding in government analysis and research?"

future_surveys:
  question: "Is there anything you would like to see in future surveys?"


rap_components:
  cols:
    use_open_source_score: "Use open source software"
    open_code_score: "Open source own code"
    version_control_score: "Version control"
    peer_review_score: "Peer review"
    qa_score: "Work to quality standards"
    doc_score: "Create project README"
    function_score: "Write functions"
    manual_test_score: "Manually test code"
    auto_test_score: "Write automated tests"
    function_doc_score: "Document functions"
    control_flow_score: "Use control flow"
    config_score: "Use configuration files"
    code_style_score: "Follow code style guidelines"
    dep_management_score: "Document dependencies"
